---
_hotel_id: SEAMDT
_portal_id: mediterranean-inn
latitude: 47.6231596
longitude: -122.35698609999997
name: zzzz...Mediterranean Inn
email: reservations@mediterranean-inn.com
phone_number: 1-206-428-4700
address:
  street1: 425 Queen Anne Avenue North
  street2: ''
  state: Washington
  city: Seattle
  country: United States
  zip_code: ''
